#! /usr/bin/node

let fs = require("fs");
let Phrase = require("./palindrome/index.js");

let text = fs.readFileSync("phrases.txt", "utf-8");
let palindromes = [];
text.split("\n").forEach((line) => {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log("palindrome detected: ", line);
    palindromes.push(phrase.content);
  }
});

fs.writeFileSync("palindromes.txt", palindromes.join("\n"));