#! /usr/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.

const request   = require("request");
const jsdom     = require("jsdom");
const { JSDOM } = jsdom;
const url       = process.argv[2];

// Exit if url is undefined.
if (!url) {
  console.log("Please set URL as a commandline argument.");
  process.exit(0);
}

request(url, function(error, response, body) {
  // Simulate a Document Object Model.
  let { document } = (new JSDOM(body)).window;
  
  // Grab all the paragraphs and references.
  let paragraphs   = document.querySelectorAll("p");
  let references   = document.querySelectorAll(".reference");

  // Remove any references.
  references.forEach(function(reference) {
    reference.remove();
  });

  // Print out all of the paragraphs.
  paragraphs.forEach(function(paragraph) {
    console.log(paragraph.textContent);
  });
});
